# Test environment configuration

spring:

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

  cloud:
    gcp:
      pubsub:
        enabled: false

  rate-limit:
    transaction-per-minute: 60
    window-seconds: 60

# Logging
logging:
  level:
    root: WARN
    com.bluebank: DEBUG
    org.hibernate.SQL: DEBUG