server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: transaction-ingestor-service
  profiles:
    active: dev
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:local-dev-project}
      pubsub:
        enabled: true

# Default configuration for local development
pubsub:
  transaction:
    topic: ${PUBSUB_TRANSACTION_TOPIC:transactions}
    emulator-host: ${PUBSUB_EMULATOR_HOST:localhost:8085}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  packages-to-scan: com.bluebank.ingestor.controller