# Production environment configuration

spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Caching configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=2000,expireAfterWrite=600s

  # Google Cloud PubSub configuration
  cloud:
    gcp:
      pubsub:
        enabled: true
        project-id: ${GCP_PROJECT_ID}
        credentials:
          location: ${GCP_CREDENTIALS_LOCATION}

# PubSub configuration
pubsub:
  emulator:
    enabled: false
  transaction:
    topic: ${PUBSUB_TRANSACTION_TOPIC}
    projectId: ${GCP_PROJECT_ID}

# Logging
logging:
  level:
    root: WARN
    com.bluebank: INFO
    org.springframework.web: WARN