server:
  port: ${PORT:8081}
  servlet:
    context-path: /api/v1/auth

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fsms_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Security configuration
jwt:
  secret: ${JWT_SECRET:default_jwt_secret_key_for_development_only}
  expiration: ${JWT_EXPIRATION:86400000}
  issuer: fsms-auth-service

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

# API documentation
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method